resources:
  - name: source_yaml
    type: GitRepo
    configuration:
      gitProvider: gitlab
      path: automation/custom_certs
      cloneProtocol: https

  - name: dummy
    type: PropertyBag
    configuration:
      hello: world

pipelines:
  - name: controller
    configuration:
      nodePool: trigger_pool
    steps:
      - name: trigger_all
        type: Bash
        configuration:
          integrations:
            - name: platform_token
          outputResources:
            - name: dummy
        execution:
          onExecute:
            - write_output dummy "parent_id=${run_id}"
            - write_output dummy "parent_url=${step_url}"
