resources:
  - name: dummy
    type: PropertyBag
    configuration:
      hello: world

pipelines:
  - name: proxy_test
    steps:
      - name: host_u20_test
        type: Bash
        configuration:
          nodePool: u20_static
          runtime:
            type: host
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - |
                if [ -n "$http_proxy" ]; then
                  echo "$http_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$https_proxy" ]; then
                  echo "$https_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$no_proxy" ]; then
                  echo "$http_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$HTTP_PROXY" ]; then
                  echo "$HTTP_PROXY"
                else
                  exit 1
                fi
            - |
                if [ -n "$HTTPS_PROXY" ]; then
                  echo "$HTTPS_PROXY"
                else
                  exit 1
                fi
            - |
                if [ -n "$NO_PROXY" ]; then
                  echo "$NO_PROXY"
                else
                  exit 1
                fi

      - name: host_c7_test
        type: Bash
        configuration:
          nodePool: c7_static
          runtime:
            type: host
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - |
                if [ -n "$http_proxy" ]; then
                  echo "$http_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$https_proxy" ]; then
                  echo "$https_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$no_proxy" ]; then
                  echo "$http_proxy"
                else
                  exit 1
                fi
            - |
                if [ -n "$HTTP_PROXY" ]; then
                  echo "$HTTP_PROXY"
                else
                  exit 1
                fi
            - |
                if [ -n "$HTTPS_PROXY" ]; then
                  echo "$HTTPS_PROXY"
                else
                  exit 1
                fi
            - |
                if [ -n "$NO_PROXY" ]; then
                  echo "$NO_PROXY"
                else
                  exit 1
                fi

      - name: container_u20_test
        type: Bash
        configuration:
          nodePool: u20_static
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "in container these values will not be set"
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"

      - name: container_c7_test
        type: Bash
        configuration:
          nodePool: c7_static
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "in container these values will not be set"
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"
