resources:
  - name: dummy
    type: PropertyBag
    configuration:
      hello: world

pipelines:
  - name: proxy_test
    steps:
      - name: host_u20_test
        type: Bash
        configuration:
          nodePool: u20_static
          runtime:
            type: host
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"

      - name: host_c7_test
        type: Bash
        configuration:
          nodePool: c7_static
          runtime:
            type: host
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"

      - name: container_u20_test
        type: Bash
        configuration:
          nodePool: u20_static
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"

      - name: container_c7_test
        type: Bash
        configuration:
          nodePool: c7_static
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - echo "$http_proxy"
            - echo "$https_proxy"
            - echo "$no_proxy"
            - echo "$HTTP_PROXY"
            - echo "$HTTPS_PROXY"
            - echo "$NO_PROXY"
